id: P23240C46
initial_creation_type: input
source_metadata:
  title: Mahāmudrā Series
  language: pt
  description: 'Lotsawa House presents the following texts on the subject of Mahāmudrā
    (phyag chen) or the ''Great Seal'':'
  volume:
    d8869b50ee654243a185b5845b10495c:
      title: Memorandum on the Subject of Mahāmudrā and Dzogchen Instructions
      parent: Advice
    f8f5689734ee4bd683686c2e831a045d:
      title: Mahāmudrā Preliminaries, Main Part & Conclusion
      parent: Advice
    664df7bb26eb440bb8017dbc4df87e66:
      title: 'Mahāmudrā: the Swift Way to Become a Lord of Realization'
      parent: Advice
    024bd2fe7920428aa103fc4a5764a40f:
      title: The Kusāli's Instruction on the Nature of Mind
      parent: Advice
    3bb8f5975276468d91b48db993b69c81:
      title: A Way of Settling into the Realization of Mind’s Essence
      parent: Advice
    ad091fbd95de4fcbb44190e3249c5e02:
      title: 'From the Mahāmudrā Preliminary Practices: Continuous Integration with
        Ground, Path, and Fruition'
      parent: Advice
    b1b8e980e9d64beb9d2891260add8686:
      title: 'Naturally Liberating Whatever You Meet: A Concise Instruction for Realizing
        the Nature of Mind'
      parent: Advice
    9fb90a9045ef40748ced039eebad98ec:
      title: Verses to Remove Hindrances and Sustain Realization of the Nature of
        Mind
      parent: Advice
    3eaac71c55e244c6ac45d228f0af1a15:
      title: The Mahāmudrā Practice of Stillness, Movement and Awareness
      parent: Advice
    a6efa41da36a46408b1f853b549e065b:
      title: Instructions on the Fivefold Mahāmudrā
      parent: Advice
    86983f013a1949dca7dc55dee0885d7d:
      title: Pointing Out Instruction
      parent: Advice
    e17498400f0445e9b0014f05f6232ef4:
      title: The Ganges Mahāmudrā Instructions
      parent: Advice
    52cf8c5138b9481cbd5f65fec6d138a7:
      title: Aspiration of the Mahāmudrā of Definitive Meaning
      parent: Aspiration Prayers
    dc86470baa3d499eab9c58119c38e339:
      title: 'A Casket of Sacred Dharma: Stages of Meditation on Dependent Arising'
      parent: Commentaries
    ae288437a5d34e478043dd6c540cd74c:
      title: The Concise Mahāmudrā Preliminaries Arranged for Recitation
      parent: Preliminaries
    8b35ba6271c44c7cbfbb78c5e54d7e4f:
      title: 'The Excellent Path of Definitive Meaning: An Unmistaken Expression of
        the Definitive Mahāmudrā'
      parent: Songs
created_at: '2022-03-01T04:32:39.534077'
last_modified_at: '2022-03-01T04:32:39.534080'
